# Podfile

require 'json'
require 'open3'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '12.1'  # minimum iOS version requise pour full-gpl

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
end

target 'SeriesFilm' do
  config = use_native_modules!

  # Ajouter la dépendance ffmpeg-kit-react-native full-gpl ici AVANT use_native_modules!
  pod '@spreen/ffmpeg-kit-react-native', 
  :subspecs => ['full-gpl'], 
  :podspec => '../node_modules/@spreen/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'


  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
